"""
Chapter 9: GRPO Math Reasoning Training — GSM8K Style
==========================================================

This script uses the GRPO algorithm to train a small language model (Qwen2.5-0.5B-Instruct)
on math reasoning tasks, demonstrating the full RLVR (Reinforcement Learning with Verifiable Rewards) pipeline.

Core pipeline:
  1. Build a GSM8K-style arithmetic word problem dataset (20 problems)
  2. Load the Qwen2.5-0.5B-Instruct model
  3. Generate group_size=4 responses per problem
  4. Compute a reward for each response with a rule-based reward function
  5. GRPO group-relative normalization to obtain advantages
  6. Update the policy using the advantages (policy gradient)
  7. Train for 3 epochs, tracking accuracy, average reward, and response length

How to run:
  pip install -r requirements.txt
  python grpo_math_reasoning.py

Notes:
  - This script can run on CPU, but it will be slow
  - A GPU is recommended (roughly 2~4 GB of VRAM needed)
  - Without a GPU, consider using a smaller model or less data
"""

import re
import copy
import torch
import numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer


# ==========================================
# Part 1: GSM8K-style math dataset
# ==========================================
# 20 elementary-school arithmetic word problems covering +, -, *, /
# Each problem contains a question and a standard answer

math_dataset = [
    {
        "question": "小明有 15 个苹果，小红给了他 27 个，小明现在有多少个苹果？",
        "answer": "42",
    },
    {
        "question": "一个班级有 36 个学生，平均分成 6 组，每组有多少个学生？",
        "answer": "6",
    },
    {
        "question": "张三每天跑步 5 公里，他一周（7天）一共跑了多少公里？",
        "answer": "35",
    },
    {
        "question": "一本书有 240 页，李四已经读了 85 页，还剩多少页没读？",
        "answer": "155",
    },
    {
        "question": "水果店有苹果 48 个，橘子 36 个，香蕉 25 个，一共有多少个水果？",
        "answer": "109",
    },
    {
        "question": "一箱饮料有 24 瓶，8 箱饮料一共有多少瓶？",
        "answer": "192",
    },
    {
        "question": "小红有 100 元钱，买了一本书花了 32 元，买了一支笔花了 8 元，还剩多少钱？",
        "answer": "60",
    },
    {
        "question": "一个长方形的长是 12 厘米，宽是 8 厘米，它的面积是多少平方厘米？",
        "answer": "96",
    },
    {
        "question": "学校买了 5 盒铅笔，每盒 12 支，一共有多少支铅笔？",
        "answer": "60",
    },
    {
        "question": "王师傅每小时加工 15 个零件，工作了 8 小时，一共加工了多少个零件？",
        "answer": "120",
    },
    {
        "question": "一列火车每小时行驶 120 公里，行驶了 3 小时，一共行驶了多少公里？",
        "answer": "360",
    },
    {
        "question": "农场里有鸡 45 只，鸭比鸡多 18 只，鸭有多少只？",
        "answer": "63",
    },
    {
        "question": "一个三角形的底边长 10 厘米，高 6 厘米，面积是多少平方厘米？",
        "answer": "30",
    },
    {
        "question": "妈妈买了 3 千克苹果，每千克 8 元，又买了 2 千克橘子，每千克 5 元，一共花了多少钱？",
        "answer": "34",
    },
    {
        "question": "学校图书馆有故事书 280 本，科技书比故事书少 95 本，科技书有多少本？",
        "answer": "185",
    },
    {
        "question": "小明从家到学校走了 15 分钟，每分钟走 60 米，家到学校有多远？",
        "answer": "900",
    },
    {
        "question": "一个游泳池长 50 米，宽 25 米，它的周长是多少米？",
        "answer": "150",
    },
    {
        "question": "有 4 个小朋友分 72 颗糖，平均每人分到多少颗？",
        "answer": "18",
    },
    {
        "question": "工厂生产了 500 个零件，合格的有 468 个，不合格的有多少个？",
        "answer": "32",
    },
    {
        "question": "一桶油重 18 千克，用掉了三分之一，还剩多少千克？",
        "answer": "12",
    },
]


# ==========================================
# Part 2: Rule-based reward function
# ==========================================
def extract_answer_from_response(response):
    """
    Extract the final answer from the model's response

    Priority order:
      1. \\boxed{...} format
      2. The number following "答案是/为：" ("the answer is:")
      3. The last number in the response (fallback)

    Args:
        response: text generated by the model
    Returns:
        str or None: the extracted answer string
    """
    # Method 1: \boxed{} format
    boxed_match = re.search(r'\\boxed\{([^}]+)\}', response)
    if boxed_match:
        return boxed_match.group(1).strip()

    # Method 2: Chinese answer marker
    cn_match = re.search(r'答案[是为：:]\s*([+-]?\d+\.?\d*)', response)
    if cn_match:
        return cn_match.group(1).strip()

    # Method 3: English answer marker
    en_match = re.search(r'[Tt]he answer is\s*([+-]?\d+\.?\d*)', response)
    if en_match:
        return en_match.group(1).strip()

    # Method 4: last number in the response (fallback)
    numbers = re.findall(r'([+-]?\d+\.?\d*)', response)
    if numbers:
        return numbers[-1]

    return None


def compute_reward(response, ground_truth):
    """
    Compute the reward value for a response

    This is a simplified reward function focused mainly on answer correctness:
      - Correct answer: reward = 1.0
      - Incorrect answer: reward = 0.0
      - Format bonus: +0.1 if step-by-step reasoning format is used
      - Well-formed response (has step markers), up to +0.1

    The final reward is capped at 1.0

    Args:
        response: text generated by the model
        ground_truth: the standard answer string
    Returns:
        float: reward value in [0.0, 1.0]
    """
    reward = 0.0

    # Extract the answer and check correctness
    extracted = extract_answer_from_response(response)
    if extracted is not None:
        try:
            if abs(float(extracted) - float(ground_truth)) < 1e-6:
                reward = 1.0
        except (ValueError, TypeError):
            if str(extracted).strip() == str(ground_truth).strip():
                reward = 1.0

    # Format bonus (only considered when the answer is correct, to avoid
    # rewarding a wrong-but-well-formatted response)
    if reward > 0:
        has_steps = bool(re.search(r'步骤|第\d+步|Step|首先|然后|接着|最后', response))
        if has_steps:
            reward = min(1.0, reward + 0.1)

    return reward


# ==========================================
# Part 3: GRPO group-relative normalization
# ==========================================
def compute_grpo_advantages(rewards):
    """
    Core of GRPO: normalize a group of rewards within the group

    Formula:
        advantage_i = (reward_i - mean) / (std + eps)

    Args:
        rewards: list[float], reward values for a group of responses
    Returns:
        numpy array: normalized advantage values
    """
    rewards_arr = np.array(rewards, dtype=np.float64)
    mean_r = rewards_arr.mean()
    std_r = rewards_arr.std() + 1e-8
    advantages = (rewards_arr - mean_r) / std_r
    return advantages


# ==========================================
# Part 4: Generate model responses
# ==========================================
def generate_responses(model, tokenizer, prompt, num_responses=4, max_new_tokens=200):
    """
    Have the model generate several different responses to the same question

    Uses do_sample=True + temperature > 0 to produce diversity.
    Each response uses a different random draw to ensure variety.

    Args:
        model: the language model
        tokenizer: the tokenizer
        prompt: the question text
        num_responses: number of responses to generate (group_size)
        max_new_tokens: max number of tokens to generate
    Returns:
        list[str]: list of generated responses
    """
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer([text], return_tensors="pt").to(model.device)

    responses = []
    for _ in range(num_responses):
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=True,
                temperature=0.7,
                top_p=0.9,
            )
        # Decode: keep only the generated part (skip the input prompt)
        response = tokenizer.decode(
            outputs[0][inputs.input_ids.shape[-1]:],
            skip_special_tokens=True,
        )
        responses.append(response)

    return responses


# ==========================================
# Part 5: GRPO policy gradient update
# ==========================================
def grpo_policy_update(model, tokenizer, optimizer, prompt, responses, advantages):
    """
    Update the model's parameters using the GRPO policy gradient

    Core formula:
        loss = -mean(advantage_i * log_prob_i)

    where log_prob_i is the log-probability of the model generating the i-th response.
    For simplicity, this implementation approximates it with the token-level average
    log-probability.

    Args:
        model: the language model
        tokenizer: the tokenizer
        optimizer: the optimizer
        prompt: the original question
        responses: list of generated responses
        advantages: GRPO-normalized advantage values
    Returns:
        float: the loss for this round
    """
    model.train()

    # Build token ids for the prompt
    messages = [{"role": "user", "content": prompt}]
    prompt_text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    prompt_ids = tokenizer.encode(prompt_text, return_tensors="pt").to(model.device)
    prompt_len = prompt_ids.shape[-1]

    total_loss = 0.0
    num_valid = 0

    for response, advantage in zip(responses, advantages):
        if advantage <= 0:
            continue  # Skip responses with non-positive advantage to save compute

        # Concatenate prompt + response
        response_ids = tokenizer.encode(response, return_tensors="pt").to(model.device)
        # Strip a possible leading BOS token from response_ids
        if response_ids[0, 0] == tokenizer.bos_token_id:
            response_ids = response_ids[:, 1:]

        full_ids = torch.cat([prompt_ids, response_ids], dim=-1)

        # Forward pass to get logits
        with torch.cuda.amp.autocast(enabled=False):
            outputs = model(full_ids)
            logits = outputs.logits

        # Compute log_prob for the generated part (response tokens only)
        # logits[:, :-1, :] corresponds to the prediction at position t; full_ids[:, 1:]
        # corresponds to the actual token at position t+1
        response_logits = logits[0, prompt_len - 1:-1, :]  # logits for the response part
        response_tokens = full_ids[0, prompt_len:]          # token ids for the response part

        if response_tokens.shape[0] == 0:
            continue

        # Compute the log-probability of each token
        log_probs = torch.nn.functional.log_softmax(response_logits, dim=-1)
        token_log_probs = log_probs.gather(1, response_tokens.unsqueeze(1)).squeeze(1)

        # Average log-probability (normalized by token count, to avoid bias toward long responses)
        avg_log_prob = token_log_probs.mean()

        # Policy gradient loss: -advantage * log_prob
        loss = -advantage * avg_log_prob
        total_loss += loss
        num_valid += 1

    if num_valid == 0:
        return 0.0

    # Average loss
    avg_loss = total_loss / num_valid

    # Backward pass and parameter update
    optimizer.zero_grad()
    avg_loss.backward()
    # Gradient clipping to prevent exploding gradients
    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
    optimizer.step()

    return avg_loss.item()


# ==========================================
# Part 6: Full training pipeline
# ==========================================
def train():
    """
    Full pipeline for GRPO math reasoning training

    Hyperparameters:
        - model_name = "Qwen/Qwen2.5-0.5B-Instruct"
        - group_size = 4: generate 4 responses per question
        - num_epochs = 3: number of training epochs
        - learning_rate = 1e-5: learning rate
        - max_new_tokens = 200: max number of generated tokens
    """
    # ---------- Hyperparameters ----------
    model_name = "Qwen/Qwen2.5-0.5B-Instruct"
    group_size = 4       # number of samples per question (the GRPO "group")
    num_epochs = 3       # number of training epochs
    learning_rate = 1e-5 # learning rate
    max_new_tokens = 200 # max generation length

    print("=" * 70)
    print("  GRPO Math Reasoning Training (GSM8K style)")
    print("=" * 70)
    print(f"  Model: {model_name}")
    print(f"  Training data: {len(math_dataset)} math problems")
    print(f"  Sample count (group_size): {group_size}")
    print(f"  Epochs: {num_epochs}")
    print(f"  Learning rate: {learning_rate}")
    print(f"  Max generation length: {max_new_tokens}")
    print("=" * 70)

    # ---------- Load the model ----------
    print("\nLoading model...")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token

    # Determine the device
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"  Using device: {device}")

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.float32,
        device_map=device,
    )
    model.eval()  # Start in eval mode

    # Create the optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

    # ---------- Pre-training test ----------
    print("\n" + "=" * 70)
    print("  Model performance before training (test on 3 sampled problems)")
    print("=" * 70)
    test_indices = [0, 7, 14]  # Test on problems 1, 8, and 15
    pre_train_results = evaluate_on_samples(model, tokenizer, math_dataset, test_indices)

    # ---------- Training loop ----------
    print("\n" + "=" * 70)
    print("  Starting GRPO training")
    print("=" * 70)

    # Track training metrics
    epoch_metrics = []

    for epoch in range(num_epochs):
        print(f"\n{'#' * 70}")
        print(f"  Epoch {epoch + 1}/{num_epochs}")
        print(f"{'#' * 70}")

        epoch_total_rewards = []
        epoch_accuracies = []
        epoch_lengths = []
        epoch_losses = []

        for idx, problem in enumerate(math_dataset):
            question = problem["question"]
            ground_truth = problem["answer"]

            # Step 1: generate a group of responses for the current question
            responses = generate_responses(
                model, tokenizer, question,
                num_responses=group_size,
                max_new_tokens=max_new_tokens,
            )

            # Step 2: compute the reward for each response
            rewards = []
            for resp in responses:
                r = compute_reward(resp, ground_truth)
                rewards.append(r)

            # Step 3: GRPO group-relative normalization
            advantages = compute_grpo_advantages(rewards)

            # Step 4: policy gradient update
            loss = grpo_policy_update(
                model, tokenizer, optimizer,
                question, responses, advantages,
            )

            # Record metrics
            avg_reward = np.mean(rewards)
            accuracy = np.mean([1.0 if r >= 1.0 else 0.0 for r in rewards])
            avg_length = np.mean([len(r) for r in responses])

            epoch_total_rewards.append(avg_reward)
            epoch_accuracies.append(accuracy)
            epoch_lengths.append(avg_length)
            epoch_losses.append(loss)

            # Print progress every 5 problems
            if (idx + 1) % 5 == 0:
                recent_acc = np.mean(epoch_accuracies[-5:])
                recent_reward = np.mean(epoch_total_rewards[-5:])
                print(
                    f"  Problem {idx + 1:2d}/{len(math_dataset)} | "
                    f"last-5 accuracy: {recent_acc:.1%} | "
                    f"avg reward: {recent_reward:.3f} | "
                    f"loss: {loss:.4f}"
                )

        # End of epoch, aggregate metrics
        epoch_metrics.append({
            "epoch": epoch + 1,
            "avg_reward": np.mean(epoch_total_rewards),
            "accuracy": np.mean(epoch_accuracies),
            "avg_length": np.mean(epoch_lengths),
            "avg_loss": np.mean([l for l in epoch_losses if l != 0.0]),
        })

        print(f"\n  Epoch {epoch + 1} summary:")
        print(f"    Avg reward:   {epoch_metrics[-1]['avg_reward']:.4f}")
        print(f"    Avg accuracy: {epoch_metrics[-1]['accuracy']:.2%}")
        print(f"    Avg response length: {epoch_metrics[-1]['avg_length']:.0f} chars")
        print(f"    Avg loss:   {epoch_metrics[-1]['avg_loss']:.4f}")

    # ---------- Post-training test ----------
    print("\n" + "=" * 70)
    print("  Model performance after training (same 3 test problems)")
    print("=" * 70)
    post_train_results = evaluate_on_samples(model, tokenizer, math_dataset, test_indices)

    # ---------- Before/after comparison ----------
    print("\n" + "=" * 70)
    print("  Before/after training comparison")
    print("=" * 70)
    for i, test_idx in enumerate(test_indices):
        problem = math_dataset[test_idx]
        pre = pre_train_results[i]
        post = post_train_results[i]
        print(f"\n  Problem: {problem['question'][:40]}...")
        print(f"  Ground truth: {problem['answer']}")
        print(f"  Before training: {pre['response'][:60]}... -> reward: {pre['reward']:.2f}")
        print(f"  After training: {post['response'][:60]}... -> reward: {post['reward']:.2f}")

    # ---------- Training metrics summary ----------
    print("\n" + "=" * 70)
    print("  Training metrics summary")
    print("=" * 70)
    print()
    print(f"  {'Epoch':>5s}  {'AvgReward':>10s}  {'Accuracy':>10s}  {'RespLen':>10s}  {'Loss':>10s}")
    print(f"  {'─────':>5s}  {'──────────':>10s}  {'──────────':>10s}  {'──────────':>10s}  {'──────────':>10s}")
    for m in epoch_metrics:
        print(f"  {m['epoch']:>5d}  {m['avg_reward']:>10.4f}  "
              f"{m['accuracy']:>10.2%}  {m['avg_length']:>10.0f}  "
              f"{m['avg_loss']:>10.4f}")

    # ---------- Final summary ----------
    print("\n" + "=" * 70)
    print("  GRPO Math Reasoning Training Summary")
    print("=" * 70)
    print(f"""
  This experiment demonstrated the full GRPO + RLVR pipeline on a math reasoning task:

  1. Data preparation:
     - {len(math_dataset)} GSM8K-style arithmetic word problems
     - Each problem has a clear standard answer, enabling rule-based verification

  2. GRPO training:
     - {group_size} responses sampled per problem
     - A rule-based reward function verifies answer correctness
     - Group-relative normalization computes advantages, with no Critic network needed
     - Policy gradient updates the model's parameters

  3. Key observations:
     - Before training: the model's outputs may be near-random, with low accuracy
     - After training: the model gradually learns the reasoning format and correct computation
     - Average reward and accuracy should steadily improve over training

  4. Comparison with DPO:
     - DPO requires paired preference data (chosen/rejected)
     - GRPO only requires a verifiable reward signal
     - For tasks with a standard answer (math, coding), GRPO + RLVR is a more natural fit

  5. Directions for extension:
     - Increase the amount of training data (the full GSM8K dataset)
     - Use a larger model (Qwen2.5-1.5B / 7B)
     - Increase group_size (8~16) for a more stable advantage estimate
     - Use a DeepSeek-R1-style multi-stage training approach
    """)


# ==========================================
# Part 7: Evaluation function
# ==========================================
def evaluate_on_samples(model, tokenizer, dataset, indices):
    """
    Evaluate the model's performance on the given samples (greedy decoding)

    Args:
        model: the language model
        tokenizer: the tokenizer
        dataset: the dataset list
        indices: sample indices to evaluate
    Returns:
        list[dict]: evaluation results for each sample
    """
    model.eval()
    results = []

    for idx in indices:
        problem = dataset[idx]
        # Use greedy decoding to generate the response (deterministic output)
        messages = [{"role": "user", "content": problem["question"]}]
        text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs = tokenizer([text], return_tensors="pt").to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=200,
                do_sample=False,
            )

        response = tokenizer.decode(
            outputs[0][inputs.input_ids.shape[-1]:],
            skip_special_tokens=True,
        )

        reward = compute_reward(response, problem["answer"])
        extracted = extract_answer_from_response(response)

        result = {
            "question": problem["question"],
            "ground_truth": problem["answer"],
            "response": response,
            "extracted_answer": extracted,
            "reward": reward,
            "correct": str(extracted) == str(problem["answer"]) if extracted else False,
        }
        results.append(result)

        # Print detailed info
        print(f"\n  Problem: {problem['question'][:50]}...")
        print(f"  Ground truth: {problem['answer']}")
        print(f"  Model response: {response[:80]}{'...' if len(response) > 80 else ''}")
        print(f"  Extracted answer: {extracted}")
        print(f"  Correct: {'yes' if result['correct'] else 'no'} | Reward: {reward:.2f}")

    return results


# ==========================================
# Entry point
# ==========================================
if __name__ == "__main__":
    train()
